In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

a_list=[1,3,5,7,9]
ser = pd.Series(a_list, index=['1st', '2nd', '3rd', '4th', '5th'], name='Odd numbers')
ser

1st    1
2nd    3
3rd    5
4th    7
5th    9
Name: Odd numbers, dtype: int64

In [ ]:
a_dict={'1st':1, '2nd':2, '3rd':3}
ser = pd.Series(a_dict,  name="natural_numbers")
ser

1st    1
2nd    2
3rd    3
Name: natural_numbers, dtype: int64

Using **Pandas Series**, perform the following:

✅ Create a Series named `scores` using the dictionary `student_scores`.

✅ Print the marks scored by **"Charlie"** and **"Eva"**.

✅ Add **5 bonus marks** to all students and print the updated Series.

✅ Display only the students who scored **above 90** after the bonus.

✅ Calculate and print the **average marks** of the class (after the bonus).

In [ ]:
student_scores={'Alice':85, 'Bob':92, 'Charlie':78, 'David':95, 'Eva':88, 'rahul':89}
scores = pd.Series(student_scores, name="scores")
scores

Alice      85
Bob        92
Charlie    78
David      95
Eva        88
rahul      89
Name: scores, dtype: int64

In [ ]:
print(f"Charlie marks: {scores['Charlie']}")
print(f"Eva marks: {scores['Eva']}")

Charlie marks: 78
Eva marks: 88

In [ ]:
scores=scores+5
scores

Alice       90
Bob         97
Charlie     83
David      100
Eva         93
rahul       94
Name: scores, dtype: int64

In [ ]:
above_ninety=scores[scores>90]
above_ninety

Bob       97
David    100
Eva       93
rahul     94
Name: scores, dtype: int64

In [ ]:
scores_average=scores.mean()
print(f"class average: {scores_average}")

class average: 92.83333333333333

In [ ]:
an_array = np.array([[25,85],[25,90],[26,70],[24,80]])
df = pd.DataFrame(an_array,index=["srikanta", "praneeth", "sagar","karun"] ,columns=['Age', 'Marks'])
df

          Age  Marks
srikanta   25     85
praneeth   25     90
sagar      26     70
karun      24     80

In [ ]:
#displaying attributes
print(df.values)
print(df.index)
print(df.columns)

[[25 85]
 [25 90]
 [26 70]
 [24 80]]
Index(['srikanta', 'praneeth', 'sagar', 'karun'], dtype='object')
Index(['Age', 'Marks'], dtype='object')

In [ ]:
#dicts of dicts
student_details={'name':['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Rahul'],
                 'age': [20, 21, 19, 22, 20, 21],
                 'marks':[85, 92, 78, 95, 88, 89]}

In [ ]:
student_df=pd.DataFrame(student_details, index=list(range(1,7)))
student_df

      name  age  marks
1    Alice   20     85
2      Bob   21     92
3  Charlie   19     78
4    David   22     95
5      Eva   20     88
6    Rahul   21     89


You are given three Series representing student data:

Names of students

Their ages

Their marks

These series are combined into a DataFrame as shown earlier.

### 🎯 Your Task:
Using the existing DataFrame, perform the following operations:

✅ Print the details (name, age, marks) of the student who scored the highest marks.

✅ Add a new student "Tharushi" with age 23 and marks 88 using the index "Th".

✅ Display the details of students who are 22 years old or older.

✅ Increase the marks of students below 80 by 10 bonus points.

✅ Calculate and print the average marks of all students after the bonus.

In [ ]:
names = pd.Series(['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Rahul'])
ages = pd.Series([20, 21, 19, 22, 20, 21])
marks = pd.Series([85, 92, 78, 95, 88, 89])
data = {'Name': names, 'Age': ages, 'Marks': marks}
student_df = pd.DataFrame(data)

In [ ]:
highest_marks_student = student_df.loc[student_df['Marks'].idxmax()]
print("Details of the student with the highest marks:")
display(highest_marks_student)

Details of the student with the highest marks:

Name     David
Age         22
Marks       95
Name: 3, dtype: object

In [ ]:
student_df.loc["Tharushi"] = [23, 88]
display(student_df)

          Age  Marks
Name
Alice      20     85
Bob        21     92
Charlie    19     78
David      22     95
Eva        20     88
Rahul      21     89
Tharushi   23     88

In [ ]:
print(student_df.loc[student_df['Age'] >= 22])

          Age  Marks
Name
David      22     95
Tharushi   23     88

In [ ]:
student_df.loc[student_df['Marks'] < 80, 'Marks'] += 10
display(student_df)

          Age  Marks
Name
Alice      20     85
Bob        21     92
Charlie    19     88
David      22     95
Eva        20     88
Rahul      21     89
Tharushi   23     88

In [ ]:
average_marks = student_df['Marks'].mean()
print(f"The average marks of all students after the bonus is: {average_marks:.2f}")

The average marks of all students after the bonus is: 89.29

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/Data_sets/data.csv'
df=pd.read_csv(path)
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

   Duration        Date  Pulse  Maxpulse  Calories
0        60  2020/12/01    110       130     409.1
1        60  2020/12/02    117       145     479.0
2        60  2020/12/03    103       135     340.0
3        45  2020/12/04    109       175     282.4
4        45  2020/12/05    117       148     406.0

In [ ]:
df.tail()

    Duration        Date  Pulse  Maxpulse  Calories
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
df.isnull()

    Duration   Date  Pulse  Maxpulse  Calories
0      False  False  False     False     False
1      False  False  False     False     False
2      False  False  False     False     False
3      False  False  False     False     False
4      False  False  False     False     False
5      False  False  False     False     False
6      False  False  False     False     False
7      False  False  False     False     False
8      False  False  False     False     False
9      False  False  False     False     False
10     False  False  False     False     False
11     False  False  False     False     False
12     False  False  False     False     False
13     False  False  False     False     False
14     False  False  False     False     False
15     False  False  False     False     False
16     False  False  False     False     False
17     False  False  False     False     False
18     False  False  False     False      True
19     False  False  False     False     False
20     False  False  False     False     False
21     False  False  False     False     False
22     False   True  False     False     False
23     False  False  False     False     False
24     False  False  False     False     False
25     False  False  False     False     False
26     False  False  False     False     False
27     False  False  False     False     False
28     False  False  False     False      True
29     False  False  False     False     False
30     False  False  False     False     False
31     False  False  False     False     False

In [ ]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [ ]:
#remove null rows
new_df=df.dropna()
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  29 non-null     int64
 1   Date      29 non-null     object
 2   Pulse     29 non-null     int64
 3   Maxpulse  29 non-null     int64
 4   Calories  29 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
#fill with some number
df.fillna(130, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      32 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  32 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
#convert to string
new_df.to_string()

'    Duration        Date  Pulse  Maxpulse  Calories\n0         60  2020/12/01    110       130     409.1\n1         60  2020/12/02    117       145     479.0\n2         60  2020/12/03    103       135     340.0\n3         45  2020/12/04    109       175     282.4\n4         45  2020/12/05    117       148     406.0\n5         60  2020/12/06    102       127     300.0\n6         60  2020/12/07    110       136     374.0\n7        450  2020/12/08    104       134     253.3\n8         30  2020/12/09    109       133     195.1\n9         60  2020/12/10     98       124     269.0\n10        60  2020/12/11    103       147     329.3\n11        60  2020/12/12    100       120     250.7\n12        60  2020/12/12    100       120     250.7\n13        60  2020/12/13    106       128     345.3\n14        60  2020/12/14    104       132     379.3\n15        60  2020/12/15     98       123     275.0\n16        60  2020/12/16     98       120     215.2\n17        60  2020/12/17    100       120     300.0\n19        60  2020/12/19    103       123     323.0\n20        45  2020/12/20     97       125     243.0\n21        60  2020/12/21    108       131     364.2\n23        60  2020/12/23    130       101     300.0\n24        45  2020/12/24    105       132     246.0\n25        60  2020/12/25    102       126     334.5\n26        60  2020/12/26    100       120     250.0\n27        60  2020/12/27     92       118     241.0\n29        60  2020/12/29    100       132     280.0\n30        60  2020/12/30    102       129     380.3\n31        60  2020/12/31     92       115     243.0'

In [ ]:
df['Calories'].fillna(130, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 1.5 KB

/tmp/ipython-input-2195015663.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calories'].fillna(130, inplace=True)

In [ ]:
#data of wrong format
df['Date']=pd.to_datetime(df['Date'], format='mixed')
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
df.dropna(subset=['Date'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 1.5 KB

In [ ]:
#focusing on wrong data:
#7 ---> Duration -----> 450

df.loc[7, 'Duration']=45
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         45 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112     130.0
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132     130.0
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
for x in df.index:
  if df.loc[x, 'Duration'] <60 :
    df.loc[x, 'Duration']=120
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3        120 2020-12-04    109       175     282.4
4        120 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        120 2020-12-08    104       134     253.3
8        120 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18       120 2020-12-18     90       112     130.0
19        60 2020-12-19    103       123     323.0
20       120 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24       120 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132     130.0
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
#checking duplicates
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [ ]:
#droping duplicates
df.drop_duplicates(inplace=True)
print(df)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3        120 2020-12-04    109       175     282.4
4        120 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        120 2020-12-08    104       134     253.3
8        120 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18       120 2020-12-18     90       112     130.0
19        60 2020-12-19    103       123     323.0
20       120 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24       120 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132     130.0
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
#filtering data
high_pulse = df.loc[df['Pulse']>110]
print(high_pulse)

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
4        120 2020-12-05    117       148     406.0
23        60 2020-12-23    130       101     300.0

In [ ]:
#sorting data
sorted_df = df.sort_values(by='Calories', ascending=False)
print(sorted_df)

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4        120 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3
6         60 2020-12-07    110       136     374.0
21        60 2020-12-21    108       131     364.2
13        60 2020-12-13    106       128     345.3
2         60 2020-12-03    103       135     340.0
25        60 2020-12-25    102       126     334.5
10        60 2020-12-11    103       147     329.3
19        60 2020-12-19    103       123     323.0
5         60 2020-12-06    102       127     300.0
17        60 2020-12-17    100       120     300.0
23        60 2020-12-23    130       101     300.0
3        120 2020-12-04    109       175     282.4
29        60 2020-12-29    100       132     280.0
15        60 2020-12-15     98       123     275.0
9         60 2020-12-10     98       124     269.0
7        120 2020-12-08    104       134     253.3
11        60 2020-12-12    100       120     250.7
26        60 2020-12-26    100       120     250.0
24       120 2020-12-24    105       132     246.0
20       120 2020-12-20     97       125     243.0
31        60 2020-12-31     92       115     243.0
27        60 2020-12-27     92       118     241.0
16        60 2020-12-16     98       120     215.2
8        120 2020-12-09    109       133     195.1
18       120 2020-12-18     90       112     130.0
28        60 2020-12-28    103       132     130.0

In [ ]:
# Create another DataFrame with Date and Trainer name
trainer_df = pd.DataFrame({
    'Date': ['2020/12/01', '2020/12/02', '2020/12/03'],
    'Trainer': ['Alex', 'Jordan', 'Taylor']
})

# Convert 'Date' column in trainer_df to datetime format
trainer_df['Date'] = pd.to_datetime(trainer_df['Date'])

# Now merge
merged_df = pd.merge(df, trainer_df, on='Date', how='left')

print(merged_df)

    Duration       Date  Pulse  Maxpulse  Calories Trainer
0         60 2020-12-01    110       130     409.1    Alex
1         60 2020-12-02    117       145     479.0  Jordan
2         60 2020-12-03    103       135     340.0  Taylor
3        120 2020-12-04    109       175     282.4     NaN
4        120 2020-12-05    117       148     406.0     NaN
5         60 2020-12-06    102       127     300.0     NaN
6         60 2020-12-07    110       136     374.0     NaN
7        120 2020-12-08    104       134     253.3     NaN
8        120 2020-12-09    109       133     195.1     NaN
9         60 2020-12-10     98       124     269.0     NaN
10        60 2020-12-11    103       147     329.3     NaN
11        60 2020-12-12    100       120     250.7     NaN
12        60 2020-12-13    106       128     345.3     NaN
13        60 2020-12-14    104       132     379.3     NaN
14        60 2020-12-15     98       123     275.0     NaN
15        60 2020-12-16     98       120     215.2     NaN
16        60 2020-12-17    100       120     300.0     NaN
17       120 2020-12-18     90       112     130.0     NaN
18        60 2020-12-19    103       123     323.0     NaN
19       120 2020-12-20     97       125     243.0     NaN
20        60 2020-12-21    108       131     364.2     NaN
21        60 2020-12-23    130       101     300.0     NaN
22       120 2020-12-24    105       132     246.0     NaN
23        60 2020-12-25    102       126     334.5     NaN
24        60 2020-12-26    100       120     250.0     NaN
25        60 2020-12-27     92       118     241.0     NaN
26        60 2020-12-28    103       132     130.0     NaN
27        60 2020-12-29    100       132     280.0     NaN
28        60 2020-12-30    102       129     380.3     NaN
29        60 2020-12-31     92       115     243.0     NaN

In [ ]:
merged_df["Trainer"].fillna("Srikanta", inplace=True)
print(merged_df)

    Duration       Date  Pulse  Maxpulse  Calories   Trainer
0         60 2020-12-01    110       130     409.1      Alex
1         60 2020-12-02    117       145     479.0    Jordan
2         60 2020-12-03    103       135     340.0    Taylor
3        120 2020-12-04    109       175     282.4  Srikanta
4        120 2020-12-05    117       148     406.0  Srikanta
5         60 2020-12-06    102       127     300.0  Srikanta
6         60 2020-12-07    110       136     374.0  Srikanta
7        120 2020-12-08    104       134     253.3  Srikanta
8        120 2020-12-09    109       133     195.1  Srikanta
9         60 2020-12-10     98       124     269.0  Srikanta
10        60 2020-12-11    103       147     329.3  Srikanta
11        60 2020-12-12    100       120     250.7  Srikanta
12        60 2020-12-13    106       128     345.3  Srikanta
13        60 2020-12-14    104       132     379.3  Srikanta
14        60 2020-12-15     98       123     275.0  Srikanta
15        60 2020-12-16     98       120     215.2  Srikanta
16        60 2020-12-17    100       120     300.0  Srikanta
17       120 2020-12-18     90       112     130.0  Srikanta
18        60 2020-12-19    103       123     323.0  Srikanta
19       120 2020-12-20     97       125     243.0  Srikanta
20        60 2020-12-21    108       131     364.2  Srikanta
21        60 2020-12-23    130       101     300.0  Srikanta
22       120 2020-12-24    105       132     246.0  Srikanta
23        60 2020-12-25    102       126     334.5  Srikanta
24        60 2020-12-26    100       120     250.0  Srikanta
25        60 2020-12-27     92       118     241.0  Srikanta
26        60 2020-12-28    103       132     130.0  Srikanta
27        60 2020-12-29    100       132     280.0  Srikanta
28        60 2020-12-30    102       129     380.3  Srikanta
29        60 2020-12-31     92       115     243.0  Srikanta

/tmp/ipython-input-797595680.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df["Trainer"].fillna("Srikanta", inplace=True)

In [ ]:
#group by duration and get average calories
avg_calories = df.groupby('Duration')['Calories'].mean()
print(avg_calories)

Duration
60     309.213043
120    250.828571
Name: Calories, dtype: float64

In [117]:
df.rename(columns={'Maxpulse':'Max_pulse'}, inplace=True)

In [118]:
df.corr()

           Duration      Date     Pulse  Max_pulse  Calories
Duration   1.000000 -0.197384  0.048504   0.335425 -0.317513
Date      -0.197384  1.000000 -0.369328  -0.517827 -0.413889
Pulse      0.048504 -0.369328  1.000000   0.261426  0.530650
Max_pulse  0.335425 -0.517827  0.261426   1.000000  0.352870
Calories  -0.317513 -0.413889  0.530650   0.352870  1.000000

In [119]:
df.describe()

         Duration                 Date       Pulse   Max_pulse    Calories
count   30.000000                   30   30.000000   30.000000   30.000000
mean    74.000000  2020-12-15 19:12:00  103.733333  129.100000  295.590000
min     60.000000  2020-12-01 00:00:00   90.000000  101.000000  130.000000
25%     60.000000  2020-12-08 06:00:00  100.000000  120.750000  247.000000
50%     60.000000  2020-12-15 12:00:00  103.000000  128.500000  291.200000
75%     60.000000  2020-12-23 18:00:00  107.500000  132.750000  343.975000
max    120.000000  2020-12-31 00:00:00  130.000000  175.000000  479.000000
std     25.810984                  NaN    8.042702   13.215325   79.102205

In [122]:
#filtering data using query and between
high_pulse_low_calories = df.query('Pulse > 110 and Calories < 400')
print("Rows with Pulse > 110 and Calories < 400:")
display(high_pulse_low_calories)

calories_between_200_and_500 = df[df['Calories'].between(200, 500)]
print("\nRows with Calories between 200 and 500:")
display(calories_between_200_and_500)

Rows with Pulse > 110 and Calories < 400:

    Duration       Date  Pulse  Max_pulse  Calories
23        60 2020-12-23    130        101     300.0

Rows with Calories between 200 and 500:

    Duration       Date  Pulse  Max_pulse  Calories
0         60 2020-12-01    110        130     409.1
1         60 2020-12-02    117        145     479.0
2         60 2020-12-03    103        135     340.0
3        120 2020-12-04    109        175     282.4
4        120 2020-12-05    117        148     406.0
5         60 2020-12-06    102        127     300.0
6         60 2020-12-07    110        136     374.0
7        120 2020-12-08    104        134     253.3
9         60 2020-12-10     98        124     269.0
10        60 2020-12-11    103        147     329.3
11        60 2020-12-12    100        120     250.7
13        60 2020-12-13    106        128     345.3
14        60 2020-12-14    104        132     379.3
15        60 2020-12-15     98        123     275.0
16        60 2020-12-16     98        120     215.2
17        60 2020-12-17    100        120     300.0
19        60 2020-12-19    103        123     323.0
20       120 2020-12-20     97        125     243.0
21        60 2020-12-21    108        131     364.2
23        60 2020-12-23    130        101     300.0
24       120 2020-12-24    105        132     246.0
25        60 2020-12-25    102        126     334.5
26        60 2020-12-26    100        120     250.0
27        60 2020-12-27     92        118     241.0
29        60 2020-12-29    100        132     280.0
30        60 2020-12-30    102        129     380.3
31        60 2020-12-31     92        115     243.0

“E-Commerce Transaction Analytics” (Using Online Retail Dataset)
🎯 Scenario / Story
You are a data analyst at ShopWave, an e-commerce platform in the UK. ShopWave logs every transaction (order) made in their store. Each record has:

Invoice number

Stock code / product ID

Description

Quantity

Invoice date

Unit price

Customer ID

Country

Your manager wants you to clean the data, fix inconsistencies, derive business metrics, and explore relationships. The cleaned data should enable deeper dashboards later.

Tasks & Steps

Below is a full pipeline of tasks that students should perform. Each task corresponds to one or more of the functions/techniques you already taught.

Load & Inspect

Read the CSV (e.g. OnlineRetail.csv)

Display head(), tail(), info(), shape

Check dtypes

Missing Data Handling

Use isnull().sum() to find missing values (e.g. some Description or Customer ID missing)

Drop rows that have missing Customer ID (because you can’t tie to a customer)

Fill missing Description or other columns using a placeholder (e.g. "Unknown")

Date Parsing / Format Correction

The InvoiceDate column might be string. Convert using pd.to_datetime(..., format='mixed')

Drop records where parsing failed (if any)

Detect & Fix Bad or Outlier Data

Some transactions might have negative quantity (returns) — detect those and decide whether to treat as returns or drop

Some unit prices might be zero or negative — fix/clean these (e.g. drop or adjust)

Duplicates

Use duplicated() to find duplicated invoice-item entries

Drop duplicates

In [124]:
path = '/content/drive/My Drive/Data_sets/OnlineRetail.csv'
df=pd.read_csv(path, encoding='latin-1')

In [154]:
print("DataFrame Head:")
print(df.head())
print("\nDataFrame Tail:")
print(df.tail())
print("\nDataFrame Info:")
print(df.info())
print("\nDataFrame Shape:")
x=df.shape
print(x)
print("\nDataFrame Data Types:")
print(df.dtypes)

DataFrame Head:
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

DataFrame Tail:
       InvoiceNo StockCode                      Description  Quantity  \
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID Country
541904 2011-12-09 12:50:00       0.85     12680.0  France
541905 2011-12-09 12:50:00       2.10     12680.0  France
541906 2011-12-09 12:50:00       4.15     12680.0  France
541907 2011-12-09 12:50:00       4.15     12680.0  France
541908 2011-12-09 12:50:00       4.95     12680.0  France

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 392692 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  object
 1   StockCode    392692 non-null  object
 2   Description  392692 non-null  object
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[ns]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  float64
 7   Country      392692 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.0+ MB
None

DataFrame Shape:
(392692, 8)

DataFrame Data Types:
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [129]:
#Missing data handling
print(df.isnull().sum())

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [133]:
#droping rows with null customer ID
df.dropna(subset=['CustomerID'], inplace=True)

In [138]:
#filling missing description with Unknown
df['Description']=df['Description'].fillna("Unknown")

In [141]:
#formating date column
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'], format='mixed')

### Detect and handle bad data

In [142]:
# Detect transactions with negative quantities
negative_quantity_transactions = df[df['Quantity'] < 0]
print("Transactions with negative quantity (returns):")
display(negative_quantity_transactions.head())
print(f"\nNumber of transactions with negative quantity: {len(negative_quantity_transactions)}")

# Decide how to handle negative quantities - for this task, let's drop them
df = df[df['Quantity'] >= 0]
print(f"\nDataFrame shape after dropping negative quantities: {df.shape}")

Transactions with negative quantity (returns):

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

Number of transactions with negative quantity: 8905

DataFrame shape after dropping negative quantities: (397924, 8)

In [145]:
# Detect transactions with zero or negative unit prices
bad_price_transactions = df[df['UnitPrice'] <= 0]
print("\nTransactions with zero or negative unit price:")
display(bad_price_transactions.head())
print(f"\nNumber of transactions with zero or negative unit price: {len(bad_price_transactions)}")

# Decide how to handle zero or negative unit prices - let's replace them with the mean
mean_unit_price = df[df['UnitPrice'] > 0]['UnitPrice'].mean()
df.loc[df['UnitPrice'] <= 0, 'UnitPrice'] = mean_unit_price

print(f"\nDataFrame shape after adjusting bad prices: {df.shape}")

Transactions with zero or negative unit price:

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

Number of transactions with zero or negative unit price: 0

DataFrame shape after adjusting bad prices: (397884, 8)

In [150]:
print(f"duplicate entries: {df.duplicated().sum()}")

duplicate entries: 5192

In [155]:
df.drop_duplicates(inplace=True)
print(df.describe())
print(f"shape of the data set after all changes {df.shape}")

            Quantity                    InvoiceDate      UnitPrice  \
count  392692.000000                         392692  392692.000000
mean       13.119702  2011-07-10 19:13:07.771892480       3.125914
min         1.000000            2010-12-01 08:26:00       0.001000
25%         2.000000            2011-04-07 11:12:00       1.250000
50%         6.000000            2011-07-31 12:02:00       1.950000
75%        12.000000            2011-10-20 12:53:00       3.750000
max     80995.000000            2011-12-09 12:50:00    8142.750000
std       180.492832                            NaN      22.241836

          CustomerID
count  392692.000000
mean    15287.843865
min     12346.000000
25%     13955.000000
50%     15150.000000
75%     16791.000000
max     18287.000000
std      1713.539549
shape of the data set after all changes (392692, 8)

In [160]:
#Filtering & Sorting
#Quantity > 1000
high_quantity_transactions=df.loc[df['Quantity']>1000]
print(high_quantity_transactions.head())
print(f"Number of transactions with quantity > 1000: {len(high_quantity_transactions)}")

      InvoiceNo StockCode                        Description  Quantity  \
4850     536809     84950     ASSORTED COLOUR T-LIGHT HOLDER      1824
4945     536830     84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS      2880
4946     536830     21915             RED  HARMONICA IN BOX       1400
6365     536890    17084R              ASSORTED INCENSE PACK      1440
16435    537659     22189            CREAM HEART CARD HOLDER      1008

              InvoiceDate  UnitPrice  CustomerID         Country
4850  2010-12-02 16:48:00       0.55     15299.0  United Kingdom
4945  2010-12-02 17:38:00       0.18     16754.0  United Kingdom
4946  2010-12-02 17:38:00       1.06     16754.0  United Kingdom
6365  2010-12-03 11:48:00       0.16     14156.0            EIRE
16435 2010-12-07 16:43:00       2.31     18102.0  United Kingdom
Number of transactions with quantity > 1000: 104

In [161]:
#highest revenue orders(sorting )-descending
#revenue=UnitPrice * Quantity
df['Revenue']=df['Quantity']*df['UnitPrice']
sorted_df=df.sort_values(by='Revenue', ascending=False)
display(sorted_df.head())

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom,168469.60
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,2011-06-10 15:28:00,649.50,15098.0,United Kingdom,38970.00
173382,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029.0,United Kingdom,8142.75
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,2011-09-20 11:05:00,5.06,17450.0,United Kingdom,7144.72

In [163]:
# Create a small custom DataFrame product_info
product_info = pd.DataFrame({
    'StockCode': ['85123A', '71053', '84406B', '84029G', '22613'],
    'Category': ['Home Decor', 'Home Decor', 'Home Decor', 'Seasonal', 'Party Supplies'],
    'Supplier': ['Supplier A', 'Supplier B', 'Supplier C', 'Supplier A', 'Supplier D']
})

print("Custom DataFrame 'product_info':")
display(product_info)

Custom DataFrame 'product_info':

  StockCode        Category    Supplier
0    85123A      Home Decor  Supplier A
1     71053      Home Decor  Supplier B
2    84406B      Home Decor  Supplier C
3    84029G        Seasonal  Supplier A
4     22613  Party Supplies  Supplier D

In [165]:
# Merge df with product_info on 'StockCode'
merged_df = pd.merge(df, product_info, on='StockCode', how='left')

print("Merged DataFrame:")
display(merged_df.head())
print(f"\nShape of the merged DataFrame: {merged_df.shape}")

Merged DataFrame:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Category,Supplier
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,Home Decor,Supplier A
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Home Decor,Supplier B
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,Home Decor,Supplier C
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Seasonal,Supplier A
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,NaN,NaN

Shape of the merged DataFrame: (392692, 11)

In [168]:
#Group by Country and compute total revenue, mean revenue per order, and count of orders
country_stats = merged_df.groupby('Country').agg({
    'Revenue': ['sum', 'mean'],
    'InvoiceNo': 'count'
})
country_stats.columns = ['Total_Revenue', 'Mean_Revenue_Per_Order', 'Count_of_Orders']
print(country_stats)

                      Total_Revenue  Mean_Revenue_Per_Order  Count_of_Orders
Country
Australia                138453.810              117.234386             1181
Austria                   10198.680               25.624824              398
Bahrain                     548.400               32.258824               17
Belgium                   41196.340               20.283772             2031
Brazil                     1143.600               35.737500               32
Canada                     3666.380               24.280662              151
Channel Islands           20440.540               27.363507              747
Cyprus                    13502.850               22.392786              603
Czech Republic              826.740               33.069600               25
Denmark                   18955.340               49.882474              380
EIRE                     265262.460               36.709446             7226
European Community         1300.250               21.670833               60
Finland                   22546.080               32.913985              685
France                   208934.310               25.094200             8326
Germany                  228678.400               25.338327             9025
Greece                     4760.520               32.831172              145
Iceland                    4310.000               23.681319              182
Israel                     7215.840               29.452408              245
Italy                     17483.240               23.064960              758
Japan                     37416.370              116.561900              321
Lebanon                    1693.880               37.641778               45
Lithuania                  1661.060               47.458857               35
Malta                      2725.590               24.335625              112
Netherlands              285446.340              121.003111             2359
Norway                    36165.440               33.767918             1071
Poland                     7334.650               22.226212              330
Portugal                  33375.840               22.970296             1453
RSA                        1002.310               17.584386               57
Saudi Arabia                145.920               16.213333                9
Singapore                 21279.290               95.852658              222
Spain                     61558.560               24.832013             2479
Sweden                    38367.830               85.261844              450
Switzerland               56443.950               30.659397             1841
USA                        3580.390               20.002179              179
United Arab Emirates       1902.280               27.974706               68
United Kingdom          7285024.644               20.861862           349203
Unspecified                2660.770               11.040539              241

In [169]:
#Rename StockCode to Product_ID, UnitPrice to Price
merged_df.rename(columns={'StockCode':'Product_ID', 'UnitPrice':'Price'})

,InvoiceNo,Product_ID,Description,Quantity,InvoiceDate,Price,CustomerID,Country,Revenue,Category,Supplier
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,Home Decor,Supplier A
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Home Decor,Supplier B
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,Home Decor,Supplier C
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Seasonal,Supplier A
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
392687,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,Party Supplies,Supplier D
392688,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,NaN,NaN
392689,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,NaN,NaN
392690,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,NaN,NaN
392691,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,NaN,NaN

In [171]:
# Use .str methods on Description
# Convert Description to lowercase for case-insensitive searching
merged_df['Description_lower'] = merged_df['Description'].str.lower()

# Filter products whose description contains "glass"
glassware_df = merged_df[merged_df['Description_lower'].str.contains('glass', na=False)]
print("Products with 'glass' in their description:")
display(glassware_df.head())

# Filter products whose description contains "christmas" or "xmas"
christmas_products = merged_df[merged_df['Description_lower'].str.contains('christmas|xmas', na=False)]
print("\nProducts with 'christmas' or 'xmas' in their description:")
display(christmas_products.head())

Products with 'glass' in their description:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Category,Supplier,Description_lower
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,25.50,NaN,NaN,glass star frosted t-light holder
64,536373,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 09:02:00,4.25,17850.0,United Kingdom,25.50,NaN,NaN,glass star frosted t-light holder
81,536375,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 09:32:00,4.25,17850.0,United Kingdom,25.50,NaN,NaN,glass star frosted t-light holder
138,536381,22778,GLASS CLOCHE SMALL,3,2010-12-01 09:41:00,3.95,15311.0,United Kingdom,11.85,NaN,NaN,glass cloche small
147,536382,22798,ANTIQUE GLASS DRESSING TABLE POT,8,2010-12-01 09:45:00,2.95,16098.0,United Kingdom,23.60,NaN,NaN,antique glass dressing table pot

Products with 'christmas' or 'xmas' in their description:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Category,Supplier,Description_lower
46,536371,22086,PAPER CHAIN KIT 50'S CHRISTMAS,80,2010-12-01 09:00:00,2.55,13748.0,United Kingdom,204.0,NaN,NaN,paper chain kit 50's christmas
122,536381,22086,PAPER CHAIN KIT 50'S CHRISTMAS,4,2010-12-01 09:41:00,2.95,15311.0,United Kingdom,11.8,NaN,NaN,paper chain kit 50's christmas
170,536385,85049A,TRADITIONAL CHRISTMAS RIBBONS,12,2010-12-01 09:56:00,1.25,17420.0,United Kingdom,15.0,NaN,NaN,traditional christmas ribbons
195,536389,22941,CHRISTMAS LIGHTS 10 REINDEER,6,2010-12-01 10:03:00,8.50,12431.0,Australia,51.0,NaN,NaN,christmas lights 10 reindeer
209,536390,22941,CHRISTMAS LIGHTS 10 REINDEER,2,2010-12-01 10:19:00,8.50,17511.0,United Kingdom,17.0,NaN,NaN,christmas lights 10 reindeer

In [173]:
merged_df.dtypes

InvoiceNo                    object
StockCode                    object
Description                  object
Quantity                      int64
InvoiceDate          datetime64[ns]
UnitPrice                   float64
CustomerID                  float64
Country                      object
Revenue                     float64
Category                     object
Supplier                     object
Description_lower            object
dtype: object

In [177]:
#Descriptive Statistics
merged_df['Country'].value_counts()

Country
United Kingdom          349203
Germany                   9025
France                    8326
EIRE                      7226
Spain                     2479
Netherlands               2359
Belgium                   2031
Switzerland               1841
Portugal                  1453
Australia                 1181
Norway                    1071
Italy                      758
Channel Islands            747
Finland                    685
Cyprus                     603
Sweden                     450
Austria                    398
Denmark                    380
Poland                     330
Japan                      321
Israel                     245
Unspecified                241
Singapore                  222
Iceland                    182
USA                        179
Canada                     151
Greece                     145
Malta                      112
United Arab Emirates        68
European Community          60
RSA                         57
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              25
Bahrain                     17
Saudi Arabia                 9
Name: count, dtype: int64

In [179]:
merged_df['Revenue'].describe()

count    392692.000000
mean         22.631500
std         311.099224
min           0.001000
25%           4.950000
50%          12.450000
75%          19.800000
max      168469.600000
Name: Revenue, dtype: float64

In [184]:
merged_df.query('Revenue > 1000 and Country == "Germany"')

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country, Revenue, Category, Supplier, Description_lower]
Index: []

In [186]:
merged_df[merged_df['Revenue'].between(10,100)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Category,Supplier,Description_lower
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,Home Decor,Supplier A,white hanging heart t-light holder
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Home Decor,Supplier B,white metal lantern
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,Home Decor,Supplier C,cream cupid hearts coat hanger
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Seasonal,Supplier A,knitted union flag hot water bottle
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,NaN,NaN,red woolly hottie white heart.
...,...,...,...,...,...,...,...,...,...,...,...,...
392687,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,Party Supplies,Supplier D,pack of 20 spaceboy napkins
392688,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,NaN,NaN,children's apron dolly girl
392689,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,NaN,NaN,childrens cutlery dolly girl
392690,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,NaN,NaN,childrens cutlery circus parade
392691,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,NaN,NaN,baking set 9 piece retrospot

In [187]:
# Define the path to save the cleaned data
output_path = '/content/drive/My Drive/Data_sets/OnlineRetail_cleaned.csv'

# Save the merged DataFrame to a CSV file
merged_df.to_csv(output_path, index=False)

print(f"Cleaned data saved successfully to {output_path}")

Cleaned data saved successfully to /content/drive/My Drive/Data_sets/OnlineRetail_cleaned.csv